var GAME_LEVELS = [
  ["  x           vvv                                                               ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x o                                                                           ",
   "  x          x      xx                                            xxx           ",
   "  x xx                      x                                    xx!xx          ",
   "  x                                                              x!v!x          ",
   "  x                                xxx                           xx=xx          ",
   "  x                                                               xvx           ",
   "  x                                                                         xx  ",
   "  x                                        xx                               |x  ",
   "  x                                                                          x  ",
   "  x         xx = xx                                                     o   |x  ",
   "  x        xxx   xxx                xx                                       x  ",
   "  x  @    xxxx o xxxx      w  x     xx                                      |x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx               x     xxxxxxx   xxxxxxxxx  ",
   "                              x= =x  xx            w x= = =x                    ",
   "                              x= =xo     xx  xx  xx xx= = =x       x            ",
   "                              x= =x                  x= = =x                    ",
   "                              xxxxxx                 xxxxxxx                    ",
   "                                                                                ",
   "                                      x                                         ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 ",
   "x          |         |        x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "x             |               x!!!!!!!xxxxxxxxxxxx                         x    ",
   "x  @                          x!!!!!!!xxxxxxxx=                            x    ",
   "xxxxxxxx         |            x!!!!!!!xxxxxx=                              x    ",
   "       xxxxxxxxxxxxxxxx       x!!!!!!!xxx=                                 x    ",
   "                  |   !       xxx| xxxx=                                   x    ",
   " o                  o !                           xxxx  xxxxxx!!!xxxx  o   x    ",
   "xxxxx                 !xx                         xxxx  xx    v  v         x    ",
   "               xxxxxxx!                       xxxxxxxxxxxx             o   x    ",
   "            w  x|     !o          |           x                            x    ",
   "        xx     x      xxxxxxxxxxxxxxxxxxxxxxxxx   o                    o   x    ",
   "               x                         x                                 x    ",
   " w             x                     o o x                                 x    ",
   "              xx              xxxxxxxxxxxx                                 x    ",
   "               x   x                                                       x    ",
   "               x|  xx                            x                         x    ",
   "x         w    x   x    x x                                                x    ",
   "              xx   x                                                       x    ",
   "       x       x|  x                                                       x    ",
   "                   x                                  x                x   x    ",
   "x                  x     x                 xx                     xxx      x    ",
   "                   x                       |x                     xxx      x    ",
   "              xx   x  w                     x                     xxx!!!!!!x    ",
   "               x   x                      o x w        w xx       xxx!!!!!!x    ",
   "    xxxx       x| xx      x      x       xx xxxxxxxxxxxxxx        xxx!!!!!!x    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        xxx!!!!!!x    ",
   "                                                                                "],
  ["                                                                                  ",
   "                                                                                  ",
   " xxxxx                                                        xxxxxx            x ",
   " x   x                                                         xxxx             x ",
   " x @ x                        o                                 xx              x ",
   " x   x                                                                          x ",
   " x   x                   xx   x  xxxxxx                                         x ",
   " x   x               xx!!!!!!!!!!!!!!!x                                        xx ",
   " x   x                 vvvvvvvvvvvvvvvx                       ||||||            x ",
   " x   x                  v    v    v   x                         oo              x ",
   " x   x                 v  v   v v  v  x                       xxxxxx            x ",
   " x   x             x   v            v x                     xxxxxxxxxx         xx ",
   " x   x                 v    v   v     x                 o xxxxx   =xxxxx o      x ",
   " x   x                   v           x                  xxxxxxxxxxxxxxxxxx      x ",
   " x   x       xx        v  v   v   xxx                   !!!!!!!!!!!!!!!!!!      x ",
   " x   xx                v  v     xx                                             xx ",
   " x   x            xx       v   x                                                x ",
   " x   x              x  v       x o                                              x ",
   " x   x            o x  v  v v v xxxxxxx                                         x ",
   " x   xx         x   x  v                                                       xx ",
   " x   x           xxx      v    v                                                x ",
   " x   x                 v        v                                               x ",
   " x   x                  v  v  v                x                               ox ",
   " x   x    x            v   v                                                   xx ",
   " x   x                       v                                                  x ",
   " x   x                 v  v     v                                               x ",
   " x   x         o       v      v                       x                         x ",
   " x   x         x        v   v                                                  xx ",
   " x   x                x   v       v                            o                x ",
   " x   x               xx  v      v                             xxx               x ",
   " x   x              xxxxx     v                                                 x ",
   " x   x            xxxxxxxx      v  v                                           xx ",
   " x              xxxxxxxxxxxx                                                   xx ",
   " x           xxxxxxxxxxxxxxxx                                            xxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx ",
   "                                                                                  "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
